name: Crowdin Download Translations

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 1,4'

jobs:
  download:
    name: Download Translations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Download Translations
      env:
        CROWDIN_AUTH_TOKEN: ${{ secrets.ZAPBOT_CROWDIN_TOKEN }}
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
      run: ./gradlew crowdinDownloadProjectTranslation && ./gradlew deployCrowdinTranslations
