name: Generate events page for website
on: 
  workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: zap-admin
    - name: Checkout zaproxy-website
      uses: actions/checkout@v3
      with:
        repository: zaproxy/zaproxy-website
        persist-credentials: false
        path: zaproxy-website
        fetch-depth: 0
    - name: Update events page
      env:
        GITHUB_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
      run: |
        # Setup git details
        export GITHUB_USER=zapbot
        git config --global user.email "12745184+zapbot@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
        # Run the ZAP script
        docker run -v $(pwd):/zap/wrk/:rw --user root -t ghcr.io/zaproxy/zaproxy:nightly ./zap.sh -addoninstallall -silent -script /zap/wrk/zap-admin/scripts/generate_events_page.js -cmd
        cd zaproxy-website
        git checkout -b update-events
        # Update the index to be sure git is aware of changes
        git update-index -q --refresh
        # Generate a PR
        git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/zaproxy-website.git
        git add site/data/events.yaml
        git commit -m "Update events page" --signoff
        git push --set-upstream origin update-events --force
        hub pull-request -b zaproxy:main --no-edit
