name: Handle Release

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - ZapVersions*.xml

jobs:
  handle-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: zap-admin
        fetch-depth: 10
    - name: Checkout zaproxy-website
      uses: actions/checkout@v4
      with:
        repository: zaproxy/zaproxy-website
        persist-credentials: false
        path: zaproxy-website
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Handle Release
      run: cd zap-admin && ./gradlew handleRelease
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
