name: Update Add-on Release

on:
  repository_dispatch:
    types: 'add-on-release'

jobs:
  add-on-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Process Client Payload
      run:  |
        echo "ADD_ON_DATA<<'EOF'" >> $GITHUB_ENV
        echo '${{ toJSON(github.event.client_payload) }}' >> $GITHUB_ENV
        echo "'EOF'" >> $GITHUB_ENV
    - name: Update Add-on Release and Create Pull Request
      run: ./gradlew updateAndCreatePullRequestAddOnRelease --envVar=ADD_ON_DATA
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
