name: Update Daily Release

on:
  repository_dispatch:
    types: 'daily-release'

jobs:
  daily-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Update Daily Release
      run: ./gradlew updateDailyRelease --url="${{ github.event.client_payload.url }}" --checksum="${{ github.event.client_payload.checksum }}"
    - name: Create Pull Request
      run: ./gradlew createPullRequestDailyRelease
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
