name: Update Main Release

on:
  repository_dispatch:
    types: 'main-release'

jobs:
  main-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Create News Main Release
      run: ./gradlew createNewsMainRelease --release="${{ github.event.client_payload.version }}"
    - name: Update Main Release
      run: ./gradlew updateMainRelease --release="${{ github.event.client_payload.version }}"
    - name: Create Pull Request
      run: ./gradlew createPullRequestMainRelease
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
